// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
/// 
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-JUh-o-rfzxpli7mIKLxkcIB16zWS9Ko',
    appId: '1:825147474551:android:e40ecb9628e0f29c0efc72',
    messagingSenderId: '825147474551',
    projectId: 'cert-a-pro',
    databaseURL: 'https://cert-a-pro-default-rtdb.firebaseio.com',
    storageBucket: 'cert-a-pro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkMzwZqSN7um6SdpgFxb48vIsSs56ZQoA',
    appId: '1:825147474551:ios:90b6921d32da7d310efc72',
    messagingSenderId: '825147474551',
    projectId: 'cert-a-pro',
    databaseURL: 'https://cert-a-pro-default-rtdb.firebaseio.com',
    storageBucket: 'cert-a-pro.appspot.com',
    iosClientId: '825147474551-89bgf8jh9rv96aktttjgv2nskr6lfaac.apps.googleusercontent.com',
    iosBundleId: 'com.example.certAPro',
  );
}
