name: cert_a_pro
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.1
  font_awesome_flutter: ^10.4.0
  cloud_firestore: ^4.5.1
  google_sign_in: ^6.1.0
  # flutter_facebook_auth: ^5.0.8
  firebase_storage: ^11.1.1
  file_picker: ^5.2.11
  # image_picker: ^0.8.7+4
  #video_player: ^2.6.1
# dependency_overrides:
#   firebase_core_platform_interface: 4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/images/
  uses-material-design: true
